language: php

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - '7.1'
  - '7.2'
  
before_install:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root

install:
  - composer install
  - php bin/console doctrine:database:create
  - php bin/console doctrine:schema:create
  - php bin/console doctrine:fixtures:load
  

