<?php
/**
 * Created by PhpStorm.
 * User: Quentin
 * Date: 26/04/2018
 * Time: 21:12
 */

namespace App\Form;


use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class InscriptionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
        ->add('email', EmailType::class, ['required'=>'true', 'attr'=>['placeholder'=>'Votre email', 'class'=>'inputFields' ]])
        ->add('Password', RepeatedType::class, array(
                'type' => PasswordType::class,
                'invalid_message' => 'Les password doivent être les mêmes.',
                'required'=>true,
                'options' => array('attr' =>['placeholder'=>'Votre mot de passe', 'class'=>'inputFields'], 'invalid_message' => 'Vos mots de passes ne sont pas les mêmes, réessayer.' ),
            ))
        ->add('submit', SubmitType::class, ['label'=>'Validez']);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        parent::configureOptions($resolver); // TODO: Change the autogenerated stub
    }

}